"use client";
import { useEffect, useRef, useState } from "react";

type Props = { open: boolean; skillName: string; submitting: boolean; error: string | null; onCancel: () => void; onConfirm: (task: string) => void | Promise<void> };
export function RunSkillDialog({ open, skillName, submitting, error, onCancel, onConfirm }: Props) {
  const [task, setTask] = useState(""); const guard = useRef(false); const textarea = useRef<HTMLTextAreaElement>(null); const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) { setTask(""); guard.current = false; return; } textarea.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !submitting) onCancel(); if (event.key === "Tab") { const nodes = Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]), textarea:not([disabled])') ?? []); if (!nodes.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if ((event.shiftKey && document.activeElement === first) || (!event.shiftKey && document.activeElement === last)) { event.preventDefault(); (event.shiftKey ? last : first).focus(); } } }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [open, onCancel, submitting]);
  if (!open) return null; const valid = task.trim().length >= 3 && task.length <= 4000;
  const submit = async () => { if (!valid || submitting || guard.current) return; guard.current = true; try { await onConfirm(task.trim()); } finally { guard.current = false; } };
  return <div className="run-modal-layer"><button className="run-modal-backdrop" aria-label="Close run confirmation" disabled={submitting} onClick={onCancel} /><div ref={dialog} role="dialog" aria-modal="true" aria-label={`Run ${skillName}`} className="run-dialog"><span>Hermes skill</span><h2>Run {skillName}</h2><label htmlFor="run-skill-task">What should this skill do?</label><textarea ref={textarea} id="run-skill-task" maxLength={4000} value={task} disabled={submitting} onChange={(event) => setTask(event.target.value)} /><div className="run-dialog-meta"><span>{task.length} / 4000</span></div>{error && <p role="alert">{error}</p>}<footer><button disabled={submitting} onClick={onCancel}>Cancel</button><button disabled={!valid || submitting} onClick={() => void submit()}>{submitting ? "Starting…" : "Confirm & Run"}</button></footer></div></div>;
}
