"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { isValidRunId, MAX_OUTPUT_TEXT, MAX_TIMELINE_EVENTS } from "@/lib/hermes/run-normalize";
import type { HermesApprovalDecision, HermesCapabilities, HermesEnvelope, HermesRunEvent, HermesRunSummary } from "@/lib/hermes/types";

export const RUN_STORAGE_KEY = "axion.hermes.active-run.v1";
const terminal = (status: HermesRunSummary["status"]) => ["completed", "failed", "cancelled"].includes(status);
type Recovery = { runId: string; skillId: string; skillName: string; createdAt: number };
async function data<T>(response: Response): Promise<T> { let envelope: HermesEnvelope<T>; try { envelope = await response.json(); } catch { throw new Error("AXION returned an invalid response."); } if (!response.ok || envelope.error || !envelope.data) throw new Error(envelope.error?.message ?? "The Hermes request failed."); return envelope.data; }

export function useHermesRun(capabilities: HermesCapabilities | null) {
  const [run, setRun] = useState<HermesRunSummary | null>(null); const [skillName, setSkillName] = useState(""); const [createdAt, setCreatedAt] = useState(0); const [timeline, setTimeline] = useState<HermesRunEvent[]>([]); const [output, setOutput] = useState(""); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [approving, setApproving] = useState(false); const [stopping, setStopping] = useState(false); const [connected, setConnected] = useState(false); const eventSource = useRef<EventSource | null>(null); const retry = useRef(0); const submitGuard = useRef(false);
  const append = useCallback((event: HermesRunEvent) => { setTimeline((items) => [...items, event].slice(-MAX_TIMELINE_EVENTS)); if (event.type === "output_delta" || event.type === "output_final") setOutput((text) => (event.type === "output_final" ? event.text : text + event.text).slice(0, MAX_OUTPUT_TEXT)); if (event.type === "status") setRun((current) => current ? { ...current, status: event.status, ...(event.status !== "waiting_for_approval" ? { approval: undefined } : {}) } : current); if (event.type === "approval_required") setRun((current) => current ? { ...current, status: "waiting_for_approval", approval: event.approval } : current); if (event.type === "failure") setError(event.message); }, []);
  const refreshStatus = useCallback(async (target = run) => { if (!target || !isValidRunId(target.runId)) return; try { const next = await data<HermesRunSummary>(await fetch(`/api/hermes/runs/${encodeURIComponent(target.runId)}`, { cache: "no-store" })); setRun({ ...next, skillId: target.skillId }); if (next.output) setOutput(next.output.slice(0, MAX_OUTPUT_TEXT)); if (terminal(next.status)) localStorage.removeItem(RUN_STORAGE_KEY); setError(next.error ?? null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to refresh run status."); } }, [run]);
  useEffect(() => { let parsed: Recovery | null = null; try { parsed = JSON.parse(localStorage.getItem(RUN_STORAGE_KEY) ?? "null"); } catch { localStorage.removeItem(RUN_STORAGE_KEY); } if (!parsed || !isValidRunId(parsed.runId) || typeof parsed.skillId !== "string" || typeof parsed.skillName !== "string" || typeof parsed.createdAt !== "number" || Date.now() - parsed.createdAt > 86_400_000) { if (parsed) localStorage.removeItem(RUN_STORAGE_KEY); return; } setRun({ runId: parsed.runId, skillId: parsed.skillId, status: "starting" }); setSkillName(parsed.skillName); setCreatedAt(parsed.createdAt); void fetch(`/api/hermes/runs/${encodeURIComponent(parsed.runId)}`, { cache: "no-store" }).then(data<HermesRunSummary>).then((next) => { setRun({ ...next, skillId: parsed!.skillId }); if (next.output) setOutput(next.output.slice(0, MAX_OUTPUT_TEXT)); if (terminal(next.status)) localStorage.removeItem(RUN_STORAGE_KEY); }).catch(() => localStorage.removeItem(RUN_STORAGE_KEY)); }, []);
  useEffect(() => { eventSource.current?.close(); if (!run || terminal(run.status)) { setConnected(false); return; } if (!capabilities?.runEventsSse) { if (!capabilities?.runStatus) return; const timer = setInterval(() => void refreshStatus(run), 3000); return () => clearInterval(timer); } const source = new EventSource(`/api/hermes/runs/${encodeURIComponent(run.runId)}/events`); eventSource.current = source; source.onopen = () => { retry.current = 0; setConnected(true); }; source.onmessage = (message) => { try { append(JSON.parse(message.data) as HermesRunEvent); } catch { /* ignore malformed browser event */ } }; source.onerror = () => { setConnected(false); source.close(); void refreshStatus(run); if (!terminal(run.status)) { retry.current = Math.min(retry.current + 1, 5); } }; return () => source.close(); }, [append, capabilities?.runEventsSse, capabilities?.runStatus, refreshStatus, run?.runId, run?.status]);
  const createRun = useCallback(async (skillId: string, name: string, task: string) => { if (submitGuard.current) return; submitGuard.current = true; setSubmitting(true); setError(null); try { const next = await data<HermesRunSummary>(await fetch("/api/hermes/runs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ skillId, task, idempotencyKey: crypto.randomUUID() }) })); const now = Date.now(); setRun(next); setSkillName(name); setCreatedAt(now); setTimeline([]); setOutput(""); localStorage.setItem(RUN_STORAGE_KEY, JSON.stringify({ runId: next.runId, skillId, skillName: name, createdAt: now } satisfies Recovery)); return next; } catch (cause) { const message = cause instanceof Error ? cause.message : "Unable to start the Hermes run."; setError(message); throw cause; } finally { setSubmitting(false); submitGuard.current = false; } }, []);
  const approve = useCallback(async (decision: HermesApprovalDecision) => { if (!run || approving) return; setApproving(true); try { await data(await fetch(`/api/hermes/runs/${encodeURIComponent(run.runId)}/approval`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision }) })); setRun((current) => current ? { ...current, status: "running", approval: undefined } : current); await refreshStatus(run); } catch (cause) { setError(cause instanceof Error ? cause.message : "Approval failed."); await refreshStatus(run); } finally { setApproving(false); } }, [approving, refreshStatus, run]);
  const stop = useCallback(async () => { if (!run || stopping) return; setStopping(true); setRun((current) => current ? { ...current, status: "stopping" } : current); try { await data(await fetch(`/api/hermes/runs/${encodeURIComponent(run.runId)}/stop`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" })); await refreshStatus({ ...run, status: "stopping" }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Stop request failed."); await refreshStatus(run); } finally { setStopping(false); } }, [refreshStatus, run, stopping]);
  const close = useCallback(() => { setRun(null); setTimeline([]); setOutput(""); setError(null); eventSource.current?.close(); }, []);
  return { run, skillName, createdAt, timeline, output, error, submitting, approving, stopping, connected, createRun, refreshStatus: () => refreshStatus(), approve, stop, close };
}
